language: python

python:
    - "2.7"
    - "3.3"
    #- "3.4"

install:
    - python setup.py --quiet install

script:
    - py.test
    - vulture setup.py vulture
    - vulture --level=0 vulture wake.py
