#! /usr/bin/env python
#
# -*- coding: utf-8 -*-
#
# vulture - Find dead code.
#
# Copyright (C) 2012  Jendrik Seipp (jendrikseipp@web.de)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import sys

import wake


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--exclude', default='',
                        help='comma-separated list of filename patterns to '
                             'exclude (e.g. svn,external)')
    parser.add_argument('-l', '--level', type=int, default=2,
                        help='higher levels result in more false positives '
                             '(default: %(default)s)')
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('--version', action='version',
                        version='%(prog)s ' + wake.__version__)
    parser.add_argument('files', nargs='+')
    args = parser.parse_args()

    if args.exclude:
        args.exclude = args.exclude.split(',')
    else:
        args.exclude = []

    return args


def main():
    args = parse_args()
    vulture = wake.Vulture(exclude=args.exclude, verbose=args.verbose,
                           level=args.level)
    vulture.scavenge(args.files)
    return 1 if vulture.report() else 0


if __name__ == '__main__':
    sys.exit(main())
